media:
  input: public/images/blog
  output: /images/blog

content:
  - name: blog
    label: Blog Posts
    path: src/content/blog
    type: collection
    fields:
      - name: title
        type: string
        required: true
      - name: metaTitle
        type: string
      - name: description
        type: text
      - name: tag
        type: select
        options:
          values:
            - Web Design
            - SEO
            - Marketing
            - Ecommerce
            - App Development
            - Branding
            - Social Media
            - Software
      - name: excerpt
        type: text
      - name: coverImage
        label: Cover Image
        type: image
      - name: author
        type: string
        default: i3Developers
      - name: authorRole
        type: string
        default: Team
      - name: publishedDate
        type: date
      - name: modifiedDate
        type: date
      - name: keywords
        type: string
        description: "Comma-separated keywords e.g. web design Lafayette, SEO Lafayette"
      - name: body
        type: rich-text
